In [1]:
import numpy as np

np.random.seed(10) # random seed to replicate results

x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3,4))
x3 = np.random.randint(10, size=(3,2,2,3))

# jon, i played around with these for about 30min trying to
# change the shape of x3 and draw how the data would look
# on my notepad. getting better!

In [2]:
print(x3.ndim) # number of dimentions
print(x3.shape) # size of each dimention
print(x3.dtype) # type of data in array

print(x3.size) # number of items in array
print(x3.itemsize) # size (in bytes) of each array element
print(x3.nbytes) # size in (in bytes) of entire array

4
(3, 2, 2, 3)
int64
36
8
288


In [3]:
x3

array([[[[1, 8, 4],
         [1, 3, 6]],

        [[5, 3, 9],
         [6, 9, 1]]],


       [[[9, 4, 2],
         [6, 7, 8]],

        [[8, 9, 2],
         [0, 6, 7]]],


       [[[8, 1, 7],
         [1, 4, 0]],

        [[8, 5, 4],
         [7, 8, 8]]]])

In [4]:
x3[0, 0, 0, 0] # with np, can access index with tuples

1

In [5]:
x3[0, 0, 0] = [99, 98, 97]  # can also use this to modify values
x3

array([[[[99, 98, 97],
         [ 1,  3,  6]],

        [[ 5,  3,  9],
         [ 6,  9,  1]]],


       [[[ 9,  4,  2],
         [ 6,  7,  8]],

        [[ 8,  9,  2],
         [ 0,  6,  7]]],


       [[[ 8,  1,  7],
         [ 1,  4,  0]],

        [[ 8,  5,  4],
         [ 7,  8,  8]]]])

In [6]:
# lets try to grab just 9,4 from x3
print(x3[1, 0, 0, :2])

# trying 5,3
print(x3[0,1,0,:2])

# trying 7,6
print(x3[1,1,1,:0:-1])

# trying 5,4
print(x3[2,1,0,1:3])

#trying 1,9,6
print(x3[0,1,1,::-1])

#trying 8,8
print(x3[2,1,1,1:3])

# trying 6,9
print(x3[0,1,1,:2])

#trying 0,6
print(x3[1,1,1,:2])

#trying 3,6
print(x3[0,0,1,1:3])

[9 4]
[5 3]
[7 6]
[5 4]
[1 9 6]
[8 8]
[6 9]
[0 6]
[3 6]


In [7]:
x4 = np.random.randint(10, size=(4,5,3))
x4

array([[[2, 6, 2],
        [8, 8, 6],
        [6, 5, 6],
        [0, 0, 6],
        [9, 1, 8]],

       [[9, 1, 2],
        [8, 9, 9],
        [5, 0, 2],
        [7, 3, 0],
        [4, 2, 0]],

       [[3, 3, 1],
        [2, 5, 9],
        [0, 1, 0],
        [1, 9, 0],
        [9, 2, 1]],

       [[1, 0, 0],
        [5, 9, 0],
        [4, 6, 6],
        [0, 2, 3],
        [3, 2, 6]]])

In [8]:
# trying 0,5
#        3,6
#        5,1
print(x4[0,:3,:2])

print("\n")

# trying 4,5,4
#        0,2,8
#        0,7,6
print(x4[3,:3,:3])

print("\n")

# trying 5
#        9
#        9
#.       7
print(x4[1,:4,1])

[[2 6]
 [8 8]
 [6 5]]


[[1 0 0]
 [5 9 0]
 [4 6 6]]


[1 9 0 3]


In [9]:
# very cool, we can use .copy() method to select and copy slices without changing the underlying data (in this case, that's x4)

x4select = x4[3,:3,:3].copy()
x4select[0,0]=99

x4select



array([[99,  0,  0],
       [ 5,  9,  0],
       [ 4,  6,  6]])

In [10]:
x4 #still unchanged

array([[[2, 6, 2],
        [8, 8, 6],
        [6, 5, 6],
        [0, 0, 6],
        [9, 1, 8]],

       [[9, 1, 2],
        [8, 9, 9],
        [5, 0, 2],
        [7, 3, 0],
        [4, 2, 0]],

       [[3, 3, 1],
        [2, 5, 9],
        [0, 1, 0],
        [1, 9, 0],
        [9, 2, 1]],

       [[1, 0, 0],
        [5, 9, 0],
        [4, 6, 6],
        [0, 2, 3],
        [3, 2, 6]]])

In [11]:
# can use reshape to lay this in one row, as long as the math works out for the new shape
# jon, this is a list within a list, is there an easy way to pop this list out of the outer list?

x4select.reshape((1,9))

array([[99,  0,  0,  5,  9,  0,  4,  6,  6]])

In [12]:
# catting arrays
# can use np.concatenate np.hstack np.vstack to get our cat on!

x5 = [1, 2, 3]
x6 = [4, 5, 6]

np.concatenate((x5, x6))

array([1, 2, 3, 4, 5, 6])

In [13]:
np.vstack((x5, x6)) #verrtical cat+stack x6 below x5

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
np.hstack((x6, x5)) #horizontally cat+stack x5 to the right of x6

array([4, 5, 6, 1, 2, 3])

In [15]:
np.vstack((x6, x5, x6)) #vertically cat+stack x6 below x5 below x6

array([[4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [16]:
# splitting arrays
# opposite of catting, follows similar logic + terminology
# np.split() np.vsplit() np.hsplit()

x0 = np.random.randint(10, size=(9))
x0

array([0, 5, 1, 3, 6, 5, 5, 1, 8])

In [17]:
x00, x000, x000 = np.split(x0, [3, 6])

In [18]:
print(x00, x000, x000)

[0 5 1] [5 1 8] [5 1 8]


In [19]:
x10 = np.random.randint(10, size=(5,5))
x10

array([[0, 5, 9, 8, 5],
       [7, 8, 5, 8, 9],
       [9, 1, 5, 9, 1],
       [4, 7, 7, 7, 9],
       [7, 6, 0, 3, 9]])

In [20]:
# pretty easy to understand after learning cat

x11, x12 = np.vsplit(x10, [2])
x12

array([[9, 1, 5, 9, 1],
       [4, 7, 7, 7, 9],
       [7, 6, 0, 3, 9]])