In [31]:
# sorting
# python has built in sort funcs, but np's are faster accross the board

import numpy as np

x = np.array([5,4,2,3,1,5,4])
np.sort(x)

array([1, 2, 3, 4, 4, 5, 5])

In [32]:
# you can also sort in place, this writes the sort to x automatically

x.sort()
print(x)

[1 2 3 4 4 5 5]


In [33]:
# np.argsort() returns the indices of the sorted elements

x = np.array([5,4,2,3,1,5,4])
i = np.argsort(x) # creates array of indices in order by value

x[i] # x at i will return values in order

array([1, 2, 3, 4, 4, 5, 5])

In [38]:
# sorting by axis

x1 = np.random.randint(5, size=(4,4))

print(np.sort(x1, axis=0)) #column sort
print("\n")
print(np.sort(x1, axis=1)) #row sort

[[0 1 1 0]
 [1 3 2 2]
 [2 4 3 2]
 [4 4 3 3]]


[[3 3 4 4]
 [1 1 1 2]
 [0 2 3 3]
 [0 2 2 4]]


In [46]:
# partitioning: np.partition for finding the n smallest items in an array
# this will front load them in the array
# note: this will not sort them, just group/partition

x2 = np.random.randint(10, size=(7,7))

In [50]:
np.partition(x2, 4, axis=0) #sorted by columns

array([[3, 2, 1, 0, 3, 2, 2],
       [1, 3, 1, 2, 2, 4, 3],
       [0, 0, 5, 2, 5, 5, 1],
       [4, 0, 6, 4, 5, 6, 5],
       [5, 4, 7, 6, 7, 6, 5],
       [6, 6, 7, 9, 8, 7, 5],
       [7, 6, 9, 9, 8, 8, 7]])