In [ ]:
# Up until now, I've learned three ways to access and modify arrays
#    - simple indices (ex: arr[0])
#    - slicing (ex: arr[:5])
#    - boolean masks (ex: arr[arr > 5])

# And now, introducing Fancy Indexiingggggg

In [33]:
import numpy as np

rand = np.random.RandomState(42)

x = rand.randint(100, size=10)
print(x)

[51 92 14 71 60 20 82 86 74 74]


In [34]:
# suppose we want to access 3 values that aren't adjacent

[x[3], x[5], x[9]]

[71, 20, 74]

In [35]:
# we can also create a list of indices we want to access

ind = [3, 5, 9]

x[ind]

array([71, 20, 74])

In [36]:
# fancy indexing molds the valus to the shape of the array holding the indices

ind = np.array([[3,5],
               [2,1]])

x[ind]

array([[71, 20],
       [14, 92]])

In [37]:
X = np.arange(12).reshape((3,4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [38]:
# this one took me a hot second to understand
# we can combine arrays within indices, with each individual
# array representing the selections for just one dimention

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

array([ 2,  5, 11])

In [39]:
#X selects 3 different values from the X array: [(0,2), (1,1), (2,3)]

In [41]:
# this also follows the rules of broadcasting, so if we combine a single row + columns, we get a 2d array

col = col.reshape((3,1))
X[row, col]


array([[ 2,  6, 10],
       [ 1,  5,  9],
       [ 3,  7, 11]])

In [43]:
# we can combine fancy indexing with other indexing methods too!

print(X)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [44]:
# fancy + simple

X[2, [0, 1, 2]]

array([ 8,  9, 10])

In [49]:
# fancy + slice
X[:2, [0,1,2]]

array([[0, 1, 2],
       [4, 5, 6]])

In [67]:
# fancy + masking

mask = np.array([1,0,1,0], dtype=bool)

X[row[:, np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [107]:
row = np.zeros((3,1), dtype=int)
X[(row[:, np.newaxis]), mask]

array([[[0, 2]],

       [[0, 2]],

       [[0, 2]]])

In [108]:
print(row)
print(mask)

[[0]
 [0]
 [0]]
[ True False  True False]


In [109]:
sum = row+mask
sum = np.array(sum, dtype=bool)
X[sum]

array([ 0,  2,  4,  6,  8, 10])