In [4]:
# jon, probably disregard this!

# making this cheat sheet for myself
# contains info that i want to retain better
# but not really info that i already know very well

import numpy as np
import pandas as pd

In [64]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])
x1 = np.random.randint(10, size=(3,3,3))
titanic = sns.load_dataset('titanic')
monte = pd.Series(['Graham Chapman', 'John Cleese', 'Terry Gilliam',
                   'Eric Idle', 'Terry Jones', 'Michael Palin'])
full_monte = pd.DataFrame({'name': monte,
                           'info': ['B|C|D', 'B|D', 'A|C',
                                    'B|D', 'B|C', 'B|C|D']})
seattle = pd.read_csv('data/Seattle2014.csv')
rainfall = np.array(seattle['PRCP'])

inches = rainfall/254.0   #1/10mm -> inches
x3 = np.random.randint(10, size=(6,6))

rng = np.random.RandomState(42)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)

index = pd.MultiIndex.from_tuples(index)
index

pop = pop.reindex(index)
pop
ser = pop

# example data

### hierarchical indices and columns
index1 = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns1 = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

### create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data


In [ ]:
# misc pandas

df.insert(0, 'column_name', 'entry');

In [7]:
# gathering array info

print('x1 shape is', x1.shape)
print('x1 number of dimentions is', x1.ndim)
print('x1 number of values is', x1.size)
print('x1 size of each value in bytes is', x1.itemsize)
print('x1 total size is', x1.size*x1.itemsize)

x1 shape is (3, 3, 3)
x1 number of dimentions is 3
x1 number of values is 27
x1 size of each value in bytes is 8
x1 total size is 216


In [8]:
# np.reduce

np.add.reduce(x1)           # reduce by adding
np.subtract.reduce(x1)      # reduce by subtraction
np.add.accumulate(x1)       # shows steps that go into reduction

reduce by adding [[16 16 12]
 [18 19 11]
 [ 8 19 19]]
reduce by subtracting [[-12   0  -2]
 [ -4  -1  -1]
 [ -2 -11  -1]]


In [10]:
# outer: in this case, multiplies the two dimentions specified (there doesn't appear to be an inner version of this)

x2 = np.arange(1,6)
x2 = np.multiply.outer(x2, x2)      # multiplies a list by itself on outter to create a 2d array
x2_centered = x2 - x2.mean(axis=0)  # centering data on the row axis
np.mean(x2_centered)                # result: 0. used to double check if x2 is indeed centered.

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [60]:
# boolean arrays

inches < 0.25;                              # produces boolean array

np.count_nonzero(inches < 0.25)             # counts nonzero values
#same as
np.sum(inches < 0.25)

np.sum((inches > 0.25) & (inches < 1))      # boolean range
inches[inches>1]                            # returns all values of True results


58

In [19]:
# sorting + partitioning

np.sort(x3) # sort function
np.sort(x3, axis=0) # column sort
np.partition(x3, 2, axis=0) #target, amount, axis

array([[0, 5, 7, 7, 8, 9],
       [5, 5, 6, 9, 9, 9],
       [2, 4, 4, 5, 7, 8],
       [0, 1, 2, 3, 7, 9],
       [1, 3, 4, 4, 4, 5],
       [0, 1, 3, 3, 6, 9]])

In [23]:
# selection

df.A  # access column 'A'
df['A']  # access column 'A'

df.iloc[0]  # access index 0 (implicit)
df.iloc[:2,:2]  # access slice (implicit)

df.loc[0]  # access index 0 (explicit, but because i[0] is also labeled 0, this is the same as iloc[0])
df.loc[:,'A':'C']  # access columns A-C (explicit)

df[df.A>6]  # boolean mask

A  B  C  D
2  7  4  3  7

In [26]:
# isnull()  -  generate a boolean mask indicating missing values
# notnull()  -  opposite of isnull()
# dropna()  -  return a filtered version of the data
# fillna()  -  return a copy of the data with missing data filled in

In [66]:
# MultiIndex

ser.unstack()                       # unstack to turn a MultiIndex into a df
ser.unstack(0)                      # specifying index level 0 to unstack
ser.unstack().stack()               # stack again to go back if you need
df.index.names = ['State', 'Year']  # naming the indices of a MultiIndex


# ways to explicitly create a MultiIndex
# pd.MultiIndex.from_arrays
# pd.MultiIndex.from_tuples
# pd.MultiIndex.from_product

# Selection in Series MultiIndex
ser['California']   # easily select any index
ser['New York', 2010]   # easily select multiple indices
ser['California':'New York']    # slicing is avail as long as MultiIndex is sorted
ser[:, 2000]    # access all 2010 entries
ser[pop > 200]  # boolean masking

# Selection in MultiIndex DFs
health_data['Guido']            # columns first, selecting all Guido's results
health_data['Guido', 'HR']      # Guido's results, only HR

# above: notice how we progress from highest level column index, to lowest level

health_data.iloc[:2, :2]        #iloc works as normal

# create a pd.IndexSlice variable
idx = pd.IndexSlice

# use variable to slice and select
# again, think outside to inside here with indexing
health_data.loc[idx[:, 1], idx[:, 'HR']]

df = df.sort_index()            # you cannot slice indices that aren't sorted
df = df.reset_index()           # create a new, blank, ordered index


ValueError: Length of new names must be 1, got 2

In [43]:
# pd.concat()

pd.concat([df1, df2])   # normal
pd.concat([df1, df2], axis=1)   # along columns
pd.concat([df1, df2], verify_integrity=True)    # will return error if repeat indices are present
pd.concat([df1, df2], keys=['A', 'B'])          # create new keys as indexes
pd.concat([df1, df2], join='inner')             # only intersection

ValueError: Indexes have overlapping values: Index([1, 2], dtype='int64')

In [ ]:
# group by column method
# show column orbital_period
# show median results

planets.groupby('method')['orbital_period'].mean()      # also median()
planets.groupby('method')['orbital_period'].count()
planets.groupby('method')['orbital_period'].first()     # also last()
planets.groupby('method')['orbital_period'].min()       # also max()
planets.groupby('method')['orbital_period'].std()       # also var()
planets.groupby('method')['orbital_period'].sum()

# why not go big?
planets.groupby('method')['orbital_period'].describe()

# can also groupby on the index levels
# planets.groupby(level=0)['distance_ft'].mean()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [ ]:
# merge()

pd.merge(df6, df7)
pd.merge(df6, df7, how='outer')     # show all results (default is inner)
pd.merge(df6, df7, how='left')      # show column results for left (df6)
pd.merge(df6, df7, on='name')       # use as key
pd.merge(df6, df7, left_index=True, right_index=True)   # can be mixed and match with left_on and right_on too!
pd.merge(df6, df7, left_on='name', right_on='name')

name   food drink
0  Mary  bread  wine

In [45]:
# pivot_table()

titanic.pivot_table('survived', index='sex', columns='class')   # 2d pivot table
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])  # 4d pivot table
titanic.pivot_table(index='sex', columns='class', 
                    aggfunc={'survived':sum, 'fare':'mean'})    # pivot table with various aggfuncs on columns
titanic.pivot_table('survived', index='sex', 
                    columns='class', margins=True)              # margins= for grouping totals



class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [50]:
# strings in pandas

monte.str.capitalize()          # .str to access string fuctions
monte.str.split()               # .split() to split up words between spaces
monte.str.extract('([A-Za-z]+)', expand=False)  # return first names
monte.str.findall(r'^[^AEIOU].*[^aeiou]$')      # findall() return names that start and end with a consonant
monte.str.slice(start=0, stop=3)    # return first three letters of entire list
full_monte['info'].str.get_dummies('|')     # separate out dummies and make new df


A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

### Methods similar to Python string methods
Nearly all Python's built-in string methods are mirrored by a Pandas vectorized string method. Here is a list of Pandas ``str`` methods that mirror Python string methods:

|             |                  |                  |                  |
|-------------|------------------|------------------|------------------|
|``len()``    | ``lower()``      | ``translate()``  | ``islower()``    | 
|``ljust()``  | ``upper()``      | ``startswith()`` | ``isupper()``    | 
|``rjust()``  | ``find()``       | ``endswith()``   | ``isnumeric()``  | 
|``center()`` | ``rfind()``      | ``isalnum()``    | ``isdecimal()``  | 
|``zfill()``  | ``index()``      | ``isalpha()``    | ``split()``      | 
|``strip()``  | ``rindex()``     | ``isdigit()``    | ``rsplit()``     | 
|``rstrip()`` | ``capitalize()`` | ``isspace()``    | ``partition()``  | 
|``lstrip()`` |  ``swapcase()``  |  ``istitle()``   | ``rpartition()`` |

Notice that these have various return values. Some, like ``lower()``, return a series of strings:

### Miscellaneous methods
Finally, there are some miscellaneous methods that enable other convenient operations:

| Method | Description |
|--------|-------------|
| ``get()`` | Index each element |
| ``slice()`` | Slice each element|
| ``slice_replace()`` | Replace slice in each element with passed value|
| ``cat()``      | Concatenate strings|
| ``repeat()`` | Repeat values |
| ``normalize()`` | Return Unicode form of string |
| ``pad()`` | Add whitespace to left, right, or both sides of strings|
| ``wrap()`` | Split long strings into lines with length less than a given width|
| ``join()`` | Join strings in each element of the Series with passed separator|
| ``get_dummies()`` | extract dummy variables as a dataframe |

### Methods similar to Python string methods
Nearly all Python's built-in string methods are mirrored by a Pandas vectorized string method. Here is a list of Pandas ``str`` methods that mirror Python string methods:

|             |                  |                  |                  |
|-------------|------------------|------------------|------------------|
|``len()``    | ``lower()``      | ``translate()``  | ``islower()``    | 
|``ljust()``  | ``upper()``      | ``startswith()`` | ``isupper()``    | 
|``rjust()``  | ``find()``       | ``endswith()``   | ``isnumeric()``  | 
|``center()`` | ``rfind()``      | ``isalnum()``    | ``isdecimal()``  | 
|``zfill()``  | ``index()``      | ``isalpha()``    | ``split()``      | 
|``strip()``  | ``rindex()``     | ``isdigit()``    | ``rsplit()``     | 
|``rstrip()`` | ``capitalize()`` | ``isspace()``    | ``partition()``  | 
|``lstrip()`` |  ``swapcase()``  |  ``istitle()``   | ``rpartition()`` |

Notice that these have various return values. Some, like ``lower()``, return a series of strings:

In [ ]:
# time in pandas

date = pd.to_datetime('4th of july, 2012')  # result: Timestamp('2012-07-04 00:00:00')
date + pd.to_timedelta(np.arange(12), 'h')  # h for hour
lebron['date'] = pd.to_datetime(lebron['date'], format='%Y-%m-%d')  # converting date column to datetime format
lebron['date'].min()    # viewing the earliest date
lebron['date'].max()    # viewing the most recent date
lebron['date'].max() - lebron['date'].min() # getting time delta between two days
filt = (lebron['date'] >= '05-18-2023') # creating filter for timeframe
lebron.loc[filt]    # using filter