In [4]:
# jon, probably disregard this!

# making this cheat sheet for myself
# contains info that i want to retain better
# but not really info that i already know very well

In [113]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

df1 = make_df('AB', [1,2])
df2 = make_df('AB', [3,4])

df6 = pd.DataFrame({'name': ['Peter', 'Paul', 'Mary'],
                    'food': ['fish', 'beans', 'bread']},
                   columns=['name', 'food'])
df7 = pd.DataFrame({'name': ['Mary', 'Joseph'],
                    'drink': ['wine', 'beer']},
                   columns=['name', 'drink'])

In [5]:
import numpy as np
import pandas as pd

x1 = np.random.randint(10, size=(3,3,3))


In [6]:
# array info

print('x1 shape is', x1.shape)
print('x1 number of dimentions is', x1.ndim)

print('x1 number of values is', x1.size)
print('x1 size of each value in bytes is', x1.itemsize)
print('x1 total size is', x1.size*x1.itemsize)

x1 shape is (3, 3, 3)
x1 number of dimentions is 3
x1 number of values is 27
x1 size of each value in bytes is 8
x1 total size is 216


In [7]:
# reduce

print('reduce by adding', np.add.reduce(x1))
print('reduce by subtracting', np.subtract.reduce(x1))

reduce by adding [[16 15 19]
 [13  8 11]
 [22 14  5]]
reduce by subtracting [[  0   3  -1]
 [-13  -2 -11]
 [ -6  -4  -5]]


In [8]:
# accumulate: shows the steps that go into reduction

np.add.accumulate(x1)

array([[[ 8,  9,  9],
        [ 0,  3,  0],
        [ 8,  5,  0]],

       [[13, 15, 10],
        [ 5,  7,  9],
        [14, 10,  3]],

       [[16, 15, 19],
        [13,  8, 11],
        [22, 14,  5]]])

In [9]:
# outer: in this case, multiplies the two dimentions specified (there doesn't appear to be an inner version of this)

x2 = np.arange(1,6)

x2 = np.multiply.outer(x2, x2)
x2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [10]:
# centering data

x2_mean = np.mean(x2, axis=0)

x2_centered = x2 - x2_mean

x2_centered

array([[ -2.,  -4.,  -6.,  -8., -10.],
       [ -1.,  -2.,  -3.,  -4.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  1.,   2.,   3.,   4.,   5.],
       [  2.,   4.,   6.,   8.,  10.]])

In [11]:
# can double check the centering works: mean should be 0

np.mean(x2_centered)

0.0

In [12]:
# boolean masks and arrays

import pandas as pd

seattle = pd.read_csv('data/Seattle2014.csv')
rainfall = np.array(seattle['PRCP'])

inches = rainfall/254.0   #1/10mm -> inches
inches.shape # shape of inches data (a list of 365 values)

(365,)

In [13]:
# boolean array
# bitwise operator produces boolean array

inches < 0.25

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True, False,

In [14]:
# boolean counting + sum

np.count_nonzero(inches < 0.25) #same as
np.sum(inches < 0.25)

299

In [15]:
# boolean range

np.sum((inches > 0.25) & (inches < 1))

58

In [16]:
# boolean + values
# syntax that will return the values where the boolean is true

inches[inches>1]

array([1.03937008, 1.83858268, 1.27165354, 1.09055118, 1.31102362,
       1.25984252, 1.3503937 ])

In [17]:
x3 = np.random.randint(10, size=(6,6))
x3

array([[1, 7, 9, 6, 4, 1],
       [4, 3, 9, 7, 8, 0],
       [8, 5, 0, 2, 2, 6],
       [8, 4, 1, 9, 7, 7],
       [9, 7, 8, 1, 5, 5],
       [5, 4, 7, 3, 1, 4]])

In [18]:
# sorting

# x2.sort() # sort in place, but i don't wanna exexute this rn
np.sort(x3) # sort function

array([[1, 1, 4, 6, 7, 9],
       [0, 3, 4, 7, 8, 9],
       [0, 2, 2, 5, 6, 8],
       [1, 4, 7, 7, 8, 9],
       [1, 5, 5, 7, 8, 9],
       [1, 3, 4, 4, 5, 7]])

In [19]:
# sort on axis

np.sort(x3, axis=0) # column sort

array([[1, 3, 0, 1, 1, 0],
       [4, 4, 1, 2, 2, 1],
       [5, 4, 7, 3, 4, 4],
       [8, 5, 8, 6, 5, 5],
       [8, 7, 9, 7, 7, 6],
       [9, 7, 9, 9, 8, 7]])

In [20]:
# partitioning

np.partition(x3, 2, axis=0) #target, amount, axis

array([[1, 3, 0, 1, 1, 0],
       [4, 4, 1, 2, 2, 1],
       [5, 4, 7, 3, 4, 4],
       [8, 7, 9, 9, 7, 7],
       [9, 7, 8, 6, 5, 5],
       [8, 5, 9, 7, 8, 6]])

In [21]:
# DataFrames

rng = np.random.RandomState(42)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])

df

A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [22]:
df.A  # access column 'A'

df['A']  # access column 'A'

df.iloc[0]  # access index 0 (implicit)
df.iloc[:2,:2]  # access slice (implicit)

df.loc[0]  # access index 0 (explicit, but because i[0] is also labeled 0, this is the same as iloc[0])
df.loc[:,'A':'C']  # access columns A-C (explicit)

df[df.A>6]  # boolean mask

A  B  C  D
2  7  4  3  7

In [23]:
df2 = df['A'] * 3 / 2
df2

0     9.0
1     9.0
2    10.5
Name: A, dtype: float64

In [24]:
df.add(df2, axis='rows')

A     B     C     D
0  15.0  12.0  16.0  13.0
1  15.0  18.0  11.0  15.0
2  17.5  14.5  13.5  17.5

In [25]:
# isnull()  -  generate a boolean mask indicating missing values
# notnull()  -  opposite of isnull()
# dropna()  -  return a filtered version of the data
# fillna()  -  return a copy of the data with missing data filled in

In [53]:
# Hierarchical Data

# example data
index = [('California', 2000), ('California', 2010),
         ('New York', 2000), ('New York', 2010),
         ('Texas', 2000), ('Texas', 2010)]
populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]
pop = pd.Series(populations, index=index)

index = pd.MultiIndex.from_tuples(index)
index

pop = pop.reindex(index)
pop
ser = pop
###


In [54]:
# unstack to turn a MultiIndex into a DataFrame

ser.unstack()

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

In [55]:
# specify the index level to unstack that index instead

ser.unstack(0)

California  New York     Texas
2000    33871648  18976457  20851820
2010    37253956  19378102  25145561

In [56]:
# stack again to go back if you need

ser.unstack().stack()

California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [57]:
# adding another column to a MultiIndex

df = pd.DataFrame({'total': pop,
                       'under18': [9267089, 9284094,
                                   4687374, 4318033,
                                   5906301, 6879014]})
df

total  under18
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [58]:
# ways to explicitly create a MultiIndex
# pd.MultiIndex.from_arrays
# pd.MultiIndex.from_tuples
# pd.MultiIndex.from_product

In [59]:
# naming the indices of a MultiIndex

df.index.names = ['State', 'Year']

In [60]:
### indexing and slicing is very different from Series to DataFrames ###

In [69]:
### Selecting in MultiIndex Series

ser['California']   # easily select any index
ser['New York', 2010]   # easily select multiple indices
ser['California':'New York']    # slicing is avail as long as MultiIndex is sorted
ser[:, 2000]    # access all 2010 entries
ser[pop > 200]  # boolean masking

State       Year
California  2000    33871648
            2010    37253956
New York    2000    18976457
            2010    19378102
Texas       2000    20851820
            2010    25145561
dtype: int64

In [71]:
# example data

### hierarchical indices and columns
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

# mock some data
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

### create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      47.0  37.5  38.0  37.7  45.0  36.9
     2      30.0  37.2  25.0  35.6  45.0  38.2
2014 1      25.0  37.6  40.0  35.0  74.0  34.6
     2      20.0  36.4  36.0  36.7  41.0  38.9

In [75]:
### Selecting in MultiIndex DataFrames

health_data['Guido']    # columns first, selecting all Guido's results
health_data['Guido', 'HR']      # Guido's results, only HR

# above: notice how we progress from highest level column index, to lowest level

health_data.iloc[:2, :2]        #iloc works as normal

# create a pd.IndexSlice variable
idx = pd.IndexSlice

# use variable to slice and select
# again, think outside to inside here with indexing
health_data.loc[idx[:, 1], idx[:, 'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      47.0  38.0  45.0
2014 1      25.0  40.0  74.0

In [76]:
# sorting is important--you cannot slice indices that aren't sorted

df = df.sort_index()

In [87]:
df.drop(columns='under18');

In [90]:
# resetting index: turn index labels into columns

df_flat = df.reset_index()
df_flat

State  Year     total  under18
0  California  2000  33871648  9267089
1  California  2010  37253956  9284094
2    New York  2000  18976457  4687374
3    New York  2010  19378102  4318033
4       Texas  2000  20851820  5906301
5       Texas  2010  25145561  6879014

In [91]:
### set index: build a MultiIndex from a DataFrame
### JDV notes this is super useful

df_flat.set_index(['State', 'Year'])

total  under18
State      Year                   
California 2000  33871648  9267089
           2010  37253956  9284094
New York   2000  18976457  4687374
           2010  19378102  4318033
Texas      2000  20851820  5906301
           2010  25145561  6879014

In [92]:
# insert 'column_name' at column 0 location with 'entry'

df.insert(0, 'column_name', 'entry');

In [107]:
# pd.concat()

pd.concat([df1, df2])   # normal
pd.concat([df1, df2], axis=1)   # along columns
pd.concat([df1, df2], verify_integrity=True)    # will return error if repeat indices are present
pd.concat([df1, df2], keys=['A', 'B'])          # create new keys as indexes
pd.concat([df1, df2], join='inner')             # only intersection

A   B
1  A1  B1
2  A2  B2
3  A3  B3
4  A4  B4

In [127]:
# group by column method
# show column orbital_period
# show median results

planets.groupby('method')['orbital_period'].mean()      # also median()
planets.groupby('method')['orbital_period'].count()
planets.groupby('method')['orbital_period'].first()     # also last()
planets.groupby('method')['orbital_period'].min()       # also max()
planets.groupby('method')['orbital_period'].std()       # also var()
planets.groupby('method')['orbital_period'].sum()

# why not go big?
planets.groupby('method')['orbital_period'].describe()

count           mean            std  \
method                                                               
Astrometry                       2.0     631.180000     544.217663   
Eclipse Timing Variations        9.0    4751.644444    2499.130945   
Imaging                         12.0  118247.737500  213978.177277   
Microlensing                     7.0    3153.571429    1113.166333   
Orbital Brightness Modulation    3.0       0.709307       0.725493   
Pulsar Timing                    5.0    7343.021201   16313.265573   
Pulsation Timing Variations      1.0    1170.000000            NaN   
Radial Velocity                553.0     823.354680    1454.926210   
Transit                        397.0      21.102073      46.185893   
Transit Timing Variations        3.0      79.783500      71.599884   

                                       min          25%           50%  \
method                                                                  
Astrometry                      246.360000   438.770000    631.180000   
Eclipse Timing Variations      1916.250000  2900.000000   4343.500000   
Imaging                        4639.150000  8343.900000  27500.000000   
Microlensing                   1825.000000  2375.000000   3300.000000   
Orbital Brightness Modulation     0.240104     0.291496      0.342887   
Pulsar Timing                     0.090706    25.262000     66.541900   
Pulsation Timing Variations    1170.000000  1170.000000   1170.000000   
Radial Velocity                   0.736540    38.021000    360.200000   
Transit                           0.355000     3.160630      5.714932   
Transit Timing Variations        22.339500    39.675250     57.011000   

                                        75%            max  
method                                                      
Astrometry                       823.590000    1016.000000  
Eclipse Timing Variations       5767.000000   10220.000000  
Imaging                        94250.000000  730000.000000  
Microlensing                    3550.000000    5100.000000  
Orbital Brightness Modulation      0.943908       1.544929  
Pulsar Timing                     98.211400   36525.000000  
Pulsation Timing Variations     1170.000000    1170.000000  
Radial Velocity                  982.000000   17337.500000  
Transit                           16.145700     331.600590  
Transit Timing Variations        108.505500     160.000000

In [122]:
# merge()

pd.merge(df6, df7)
pd.merge(df6, df7, how='outer')     # show all results (default is inner)
pd.merge(df6, df7, how='left')      # show column results for left (df6)
pd.merge(df6, df7, on='name')       # use as key
pd.merge(df6, df7, left_index=True, right_index=True)   # can be mixed and match with left_on and right_on too!
pd.merge(df6, df7, left_on='name', right_on='name')

name   food drink
0  Mary  bread  wine