In [100]:
# jon, probably disregard this!

# making this cheat sheet for myself
# contains info that i want to retain better
# but not really info that i already know very well

In [101]:
import numpy as np

x1 = np.random.randint(10, size=(3,3,3))


In [102]:
# array info

print('x1 shape is', x1.shape)
print('x1 number of dimentions is', x1.ndim)

print('x1 number of values is', x1.size)
print('x1 size of each value in bytes is', x1.itemsize)
print('x1 total size is', x1.size*x1.itemsize)

x1 shape is (3, 3, 3)
x1 number of dimentions is 3
x1 number of values is 27
x1 size of each value in bytes is 8
x1 total size is 216


In [103]:
# reduce

print('reduce by adding', np.add.reduce(x1))
print('reduce by subtracting', np.subtract.reduce(x1))

reduce by adding [[14 26  4]
 [11 18 13]
 [11 18  9]]
reduce by subtracting [[-6 -8 -4]
 [-7 -6 -1]
 [ 5  0  1]]


In [104]:
# accumulate: shows the steps that go into reduction

np.add.accumulate(x1)

array([[[ 4,  9,  0],
        [ 2,  6,  6],
        [ 8,  9,  5]],

       [[ 8, 17,  3],
        [11, 14,  7],
        [10, 11,  8]],

       [[14, 26,  4],
        [11, 18, 13],
        [11, 18,  9]]])

In [105]:
# outer: in this case, multiplies the two dimentions specified (there doesn't appear to be an inner version of this)

x2 = np.arange(1,6)

x2 = np.multiply.outer(x2, x2)
x2

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

In [106]:
# centering data

x2_mean = np.mean(x2, axis=0)

x2_centered = x2 - x2_mean

x2_centered

array([[ -2.,  -4.,  -6.,  -8., -10.],
       [ -1.,  -2.,  -3.,  -4.,  -5.],
       [  0.,   0.,   0.,   0.,   0.],
       [  1.,   2.,   3.,   4.,   5.],
       [  2.,   4.,   6.,   8.,  10.]])

In [107]:
# can double check the centering works: mean should be 0

np.mean(x2_centered)

0.0

In [108]:
# boolean masks and arrays

import pandas as pd

seattle = pd.read_csv('data/Seattle2014.csv')
rainfall = np.array(seattle['PRCP'])

inches = rainfall/254.0   #1/10mm -> inches
inches.shape # shape of inches data (a list of 365 values)

(365,)

In [109]:
# boolean array
# bitwise operator produces boolean array

inches < 0.25

array([ True,  True,  True,  True,  True,  True, False, False,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False, False,  True,  True, False,
       False, False, False, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False, False, False,
       False,  True,  True, False,  True, False,  True,  True,  True,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False, False,  True,
       False,  True,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True, False,

In [110]:
# boolean counting + sum

np.count_nonzero(inches < 0.25) #same as
np.sum(inches < 0.25)

299

In [111]:
# boolean range

np.sum((inches > 0.25) & (inches < 1))

58

In [112]:
# boolean + values
# syntax that will return the values where the boolean is true

inches[inches>1]

array([1.03937008, 1.83858268, 1.27165354, 1.09055118, 1.31102362,
       1.25984252, 1.3503937 ])

In [113]:
x3 = np.random.randint(10, size=(6,6))
x3

array([[8, 1, 4, 3, 3, 0],
       [5, 3, 4, 4, 9, 6],
       [9, 5, 0, 4, 2, 4],
       [2, 8, 9, 3, 3, 6],
       [8, 0, 2, 1, 3, 8],
       [5, 9, 1, 1, 7, 1]])

In [114]:
# sorting

# x2.sort() # sort in place, but i don't wanna exexute this rn
np.sort(x3) # sort function

array([[0, 1, 3, 3, 4, 8],
       [3, 4, 4, 5, 6, 9],
       [0, 2, 4, 4, 5, 9],
       [2, 3, 3, 6, 8, 9],
       [0, 1, 2, 3, 8, 8],
       [1, 1, 1, 5, 7, 9]])

In [115]:
# sort on axis

np.sort(x3, axis=0) # column sort

array([[2, 0, 0, 1, 2, 0],
       [5, 1, 1, 1, 3, 1],
       [5, 3, 2, 3, 3, 4],
       [8, 5, 4, 3, 3, 6],
       [8, 8, 4, 4, 7, 6],
       [9, 9, 9, 4, 9, 8]])

In [116]:
# partitioning

np.partition(x3, 2, axis=0) #target, amount, axis

array([[2, 0, 0, 1, 2, 0],
       [5, 1, 1, 1, 3, 1],
       [5, 3, 2, 3, 3, 4],
       [8, 8, 9, 4, 9, 6],
       [8, 5, 4, 3, 3, 8],
       [9, 9, 4, 4, 7, 6]])

In [117]:
# DataFrames

rng = np.random.RandomState(42)
df = pd.DataFrame(rng.randint(0, 10, (3, 4)),
                  columns=['A', 'B', 'C', 'D'])

df

A  B  C  D
0  6  3  7  4
1  6  9  2  6
2  7  4  3  7

In [132]:
df.A  # access column 'A'

df['A']  # access column 'A'

df.iloc[0]  # access index 0 (implicit)
df.iloc[:2,:2]  # access slice (implicit)

df.loc[0]  # access index 0 (explicit, but because i[0] is also labeled 0, this is the same as iloc[0])
df.loc[:,'A':'C']  # access columns A-C (explicit)

df[df.A>6]  # boolean mask

A  B  C  D
2  7  4  3  7

In [141]:
df2 = df['A'] * 3 / 2
df2

0     9.0
1     9.0
2    10.5
Name: A, dtype: float64

In [146]:
df.add(df2, axis='rows')

A     B     C     D
0  15.0  12.0  16.0  13.0
1  15.0  18.0  11.0  15.0
2  17.5  14.5  13.5  17.5

In [ ]:
# isnull()  -  generate a boolean mask indicating missing values
# notnull()  -  opposite of isnull()
# dropna()  -  return a filtered version of the data
# fillna()  -  return a copy of the data with missing data filled in