In [2]:
# jon, probably disregard this!

# using this journal to code whatever comes to mind
# primary focus is to get muscle/mind memory working better

import numpy as np

x3 = [[10, 10, 10],
      [10, 10, 10]]

In [3]:
x3[0][0]

10

In [4]:
x2 = np.random.randint(10, size=[2,2,3])

In [5]:
x2

array([[[4, 8, 5],
        [2, 0, 2]],

       [[1, 3, 3],
        [3, 6, 2]]])

In [6]:
x2 = np.random.randint(10, size=(2,2))

In [7]:
x2

array([[9, 5],
       [2, 0]])

In [8]:
a = np.random.randint(10, size=[4,4])
a

array([[2, 5, 5, 8],
       [1, 6, 1, 3],
       [5, 3, 7, 6],
       [5, 3, 2, 6]])

In [9]:
c = np.hsplit(a, [2])

In [10]:
np.vsplit(a, [2])

[array([[2, 5, 5, 8],
        [1, 6, 1, 3]]),
 array([[5, 3, 7, 6],
        [5, 3, 2, 6]])]

In [11]:
b = a[2,1:3].copy()

In [12]:
b[0]

3

In [13]:
b[1]

7

In [14]:
c[0]

array([[2, 5],
       [1, 6],
       [5, 3],
       [5, 3]])

In [15]:
b

array([3, 7])

In [16]:
c = np.vstack([c[0], b])

In [17]:
c

array([[2, 5],
       [1, 6],
       [5, 3],
       [5, 3],
       [3, 7]])

In [18]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [20]:
w = np.vstack((z, y))
w

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.hsplit(w, [2])

[array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])]

In [22]:
a = np.arange(16).reshape((4,4))
a + 1
a = np.vsplit(a, [2])

#a = np.add.reduce(a)

for i in range(np.ndim(a)):
    a = np.add.reduce(a)
    
a

120

In [23]:
np.ndim(a)

0

In [24]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [25]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [26]:
np.random.random((2,2))

array([[0.01302096, 0.2214815 ],
       [0.14608716, 0.28093762]])

In [27]:
np.random.normal(0, 100, size=(2,2))

array([[ 44.71463527,  63.13033975],
       [125.93078215, -42.67882882]])

In [28]:
np.eye(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [29]:
x1 = np.random.randint(10, size=(3,3,3,3))
x1

array([[[[1, 6, 9],
         [9, 2, 9],
         [3, 6, 2]],

        [[3, 7, 4],
         [5, 2, 7],
         [5, 2, 5]],

        [[7, 6, 4],
         [7, 9, 2],
         [8, 1, 0]]],


       [[[5, 5, 4],
         [0, 9, 2],
         [9, 8, 4]],

        [[4, 9, 5],
         [8, 1, 2],
         [3, 7, 5]],

        [[1, 6, 8],
         [0, 9, 0],
         [0, 6, 4]]],


       [[[6, 0, 3],
         [0, 7, 9],
         [7, 5, 2]],

        [[6, 4, 6],
         [1, 9, 2],
         [2, 6, 3]],

        [[4, 5, 9],
         [9, 6, 2],
         [6, 2, 3]]]])

In [30]:
x1[0,0,1,0]

9

In [31]:
x1[1,1,0,0]

4

In [32]:
x1[1,0,:,:1]

array([[5],
       [0],
       [9]])

In [34]:
L = np.arange(10)

In [35]:
type(L)

numpy.ndarray

In [45]:
x1 = np.random.randint(10, size=(3,3,3))

# these seem really important as they quickly tell you info about the array
print(x1.shape) # shape of entire array.
print(x1.ndim) # number of dimentions. almost as useful as shape.
print(x1.itemsize*x1.size) # total bytes in array = size*itemsize



(3, 3, 3)
3
216
