In [99]:
# jon, probably disregard this!

# using this journal to code whatever comes to mind
# primary focus is to get muscle/mind memory working better

import numpy as np
import pandas as pd

x3 = [[10, 10, 10],
      [10, 10, 10]]

In [100]:
x3[0][0]

10

In [101]:
x2 = np.random.randint(10, size=[2,2,3])

In [102]:
x2

array([[[3, 3, 6],
        [9, 9, 9]],

       [[3, 4, 5],
        [3, 1, 3]]])

In [103]:
x2 = np.random.randint(10, size=(2,2))

In [104]:
x2

array([[8, 7],
       [5, 2]])

In [105]:
a = np.random.randint(10, size=[4,4])
a

array([[5, 5, 9, 1],
       [8, 1, 8, 4],
       [2, 0, 0, 8],
       [6, 5, 7, 0]])

In [106]:
c = np.hsplit(a, [2])

In [107]:
np.vsplit(a, [2])

[array([[5, 5, 9, 1],
        [8, 1, 8, 4]]),
 array([[2, 0, 0, 8],
        [6, 5, 7, 0]])]

In [108]:
b = a[2,1:3].copy()

In [109]:
b[0]

0

In [110]:
b[1]

0

In [111]:
c[0]

array([[5, 5],
       [8, 1],
       [2, 0],
       [6, 5]])

In [112]:
b

array([0, 0])

In [113]:
c = np.vstack([c[0], b])

In [114]:
c

array([[5, 5],
       [8, 1],
       [2, 0],
       [6, 5],
       [0, 0]])

In [115]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [116]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [117]:
w = np.vstack((z, y))
w

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [118]:
np.hsplit(w, [2])

[array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])]

In [119]:
a = np.arange(16).reshape((4,4))
a + 1
a = np.vsplit(a, [2])

#a = np.add.reduce(a)

for i in range(np.ndim(a)):
    a = np.add.reduce(a)
    
a

120

In [120]:
np.ndim(a)

0

In [121]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [122]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [123]:
np.random.random((2,2))

array([[0.10640269, 0.00509324],
       [0.33337549, 0.46653021]])

In [124]:
np.random.normal(0, 100, size=(2,2))

array([[-133.90194244,  225.15498467],
       [-129.86469351,  -81.56633925]])

In [125]:
np.eye(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [126]:
x1 = np.random.randint(10, size=(3,3,3,3))
x1

array([[[[8, 2, 0],
         [0, 4, 4],
         [1, 9, 5]],

        [[7, 8, 1],
         [2, 3, 7],
         [2, 4, 7]],

        [[2, 6, 7],
         [9, 1, 6],
         [3, 6, 0]]],


       [[[0, 8, 8],
         [9, 8, 2],
         [4, 7, 8]],

        [[9, 1, 5],
         [6, 8, 9],
         [3, 2, 6]],

        [[4, 4, 1],
         [9, 2, 8],
         [3, 6, 8]]],


       [[[4, 4, 7],
         [6, 6, 0],
         [6, 5, 5]],

        [[5, 5, 3],
         [0, 8, 1],
         [2, 6, 0]],

        [[7, 2, 7],
         [0, 0, 2],
         [6, 9, 1]]]])

In [127]:
x1[0,0,1,0]

0

In [128]:
x1[1,1,0,0]

9

In [129]:
x1[1,0,:,:1]

array([[0],
       [9],
       [4]])

In [130]:
L = np.arange(10)

In [131]:
type(L)

numpy.ndarray

In [132]:
x1 = np.random.randint(10, size=(3,3,3))

# these seem really important as they quickly tell you info about the array
print(x1.shape) # shape of entire array.
print(x1.ndim) # number of dimentions. almost as useful as shape.
print(x1.itemsize*x1.size) # total bytes in array = size*itemsize



(3, 3, 3)
3
216


In [133]:

import pandas as pd

In [134]:
data = [[1, 100], [2, 200], [3, 300]]
employee = pd.DataFrame(data, columns=['Id', 'Salary']).astype({'Id':'Int64', 'Salary':'Int64'})

In [135]:
def nth_highest_salary(employee: pd.DataFrame, N: int) -> pd.DataFrame:
    employee = employee.sort_values('Salary', ascending=False)
    N += 1
    return employee.iloc[N, :2]

In [136]:
employee = employee.sort_values('Salary', ascending=False)
employee.iloc[2, 1]

100

In [137]:
x1

array([[[8, 2, 0],
        [8, 6, 3],
        [3, 8, 0]],

       [[5, 6, 2],
        [7, 3, 1],
        [3, 7, 8]],

       [[3, 4, 4],
        [9, 0, 1],
        [6, 2, 6]]])

In [138]:
x1[1,0,0:2]
x1.size*x1.itemsize

216

In [139]:
x1 = x1.astype('int8')

In [140]:
x1.size*x1.itemsize

27

In [143]:
df = pd.DataFrame(x1[0])
df

0  1  2
0  8  2  0
1  8  6  3
2  3  8  0