In [12]:
# using this journal to code whatever comes to mind
# primary focus is to get muscle/mind memory working better

import numpy as np

x3 = [[10, 10, 10],
      [10, 10, 10]]

In [13]:
x3[0][0]

10

In [15]:
x2 = np.random.randint(10, size=[2,2,3])

In [16]:
x2

array([[[0, 5, 1],
        [2, 1, 9]],

       [[6, 1, 6],
        [1, 6, 7]]])

In [17]:
x2 = np.random.randint(10, size=(2,2))

In [18]:
x2

array([[2, 6],
       [4, 1]])

In [20]:
a = np.random.randint(10, size=[4,4])
a

array([[7, 7, 1, 1],
       [4, 0, 0, 8],
       [1, 7, 9, 8],
       [7, 4, 4, 0]])

In [40]:
c = np.hsplit(a, [2])

In [25]:
np.vsplit(a, [2])

[array([[7, 7, 1, 1],
        [4, 0, 0, 8]]),
 array([[1, 7, 9, 8],
        [7, 4, 4, 0]])]

In [36]:
b = a[2,1:3].copy()

In [38]:
b[0]

7

In [51]:
b[1]

9

In [56]:
c[0]

array([[7, 7],
       [4, 0],
       [1, 7],
       [7, 4]])

In [54]:
b

array([7, 9])

In [58]:
c = np.vstack([c[0], b])

In [59]:
c

array([[7, 7],
       [4, 0],
       [1, 7],
       [7, 4],
       [7, 9]])

In [67]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [72]:
w = np.vstack((z, y))
w

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [141]:
np.hsplit(w, [2])

[array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])]

In [142]:
a = np.arange(16).reshape((4,4))
a + 1
a = np.vsplit(a, [2])

#a = np.add.reduce(a)

for i in range(np.ndim(a)):
    a = np.add.reduce(a)
    
a

120

In [143]:
np.ndim(a)

0