In [6]:
# using this journal to code whatever comes to mind
# primary focus is to get muscle/mind memory working better

import numpy as np

x3 = [[10, 10, 10],
      [10, 10, 10]]

In [7]:
x3[0][0]

10

In [8]:
x2 = np.random.randint(10, size=[2,2,3])

In [9]:
x2

array([[[9, 5, 7],
        [4, 7, 3]],

       [[8, 9, 4],
        [4, 9, 0]]])

In [10]:
x2 = np.random.randint(10, size=(2,2))

In [11]:
x2

array([[5, 1],
       [2, 7]])

In [12]:
a = np.random.randint(10, size=[4,4])
a

array([[1, 1, 3, 5],
       [0, 6, 9, 2],
       [8, 9, 5, 4],
       [0, 2, 1, 4]])

In [13]:
c = np.hsplit(a, [2])

In [14]:
np.vsplit(a, [2])

[array([[1, 1, 3, 5],
        [0, 6, 9, 2]]),
 array([[8, 9, 5, 4],
        [0, 2, 1, 4]])]

In [15]:
b = a[2,1:3].copy()

In [16]:
b[0]

9

In [17]:
b[1]

5

In [18]:
c[0]

array([[1, 1],
       [0, 6],
       [8, 9],
       [0, 2]])

In [19]:
b

array([9, 5])

In [20]:
c = np.vstack([c[0], b])

In [21]:
c

array([[1, 1],
       [0, 6],
       [8, 9],
       [0, 2],
       [9, 5]])

In [22]:
z = np.ones((5, 5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
y = np.zeros(5)
y

array([0., 0., 0., 0., 0.])

In [24]:
w = np.vstack((z, y))
w

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [25]:
np.hsplit(w, [2])

[array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [0., 0.]]),
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [0., 0., 0.]])]

In [26]:
a = np.arange(16).reshape((4,4))
a + 1
a = np.vsplit(a, [2])

#a = np.add.reduce(a)

for i in range(np.ndim(a)):
    a = np.add.reduce(a)
    
a

120

In [27]:
np.ndim(a)

0

In [30]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [38]:
np.linspace(0, np.pi, 20)

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

In [40]:
np.random.random((2,2))

array([[0.55343685, 0.65511661],
       [0.34932792, 0.80972324]])

In [42]:
np.random.normal(0, 100, size=(2,2))

array([[ 66.51065221, -92.54024083],
       [ 66.30738283, 156.66491969]])

In [43]:
np.eye(3, dtype=bool)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [45]:
x1 = np.random.randint(10, size=(3,3,3,3))
x1

array([[[[2, 2, 8],
         [9, 9, 5],
         [9, 0, 8]],

        [[4, 0, 8],
         [7, 4, 6],
         [2, 8, 1]],

        [[8, 5, 2],
         [2, 4, 4],
         [2, 3, 1]]],


       [[[1, 9, 9],
         [4, 2, 9],
         [3, 0, 6]],

        [[9, 1, 1],
         [5, 0, 6],
         [1, 0, 7]],

        [[6, 6, 8],
         [5, 9, 2],
         [3, 6, 1]]],


       [[[4, 4, 5],
         [1, 2, 8],
         [1, 0, 4]],

        [[5, 7, 8],
         [1, 4, 1],
         [1, 2, 1]],

        [[8, 6, 3],
         [8, 7, 5],
         [9, 0, 6]]]])

In [47]:
x1[0,0,1,0]

9

In [48]:
x1[1,1,0,0]

9

In [52]:
x1[1,0,:,:1]

array([[1],
       [4],
       [3]])